-- Códigos para data e horário
alter session set nls_date_format='dd/mm/yyyy hh24:mi:ss';
alter session set time_zone='-3:00';


-- Cadastrar Bonificação  ok
CREATE OR REPLACE PROCEDURE CADASTRAR_BONIFICAÇÃO (CODIGO VARCHAR2, VALOR NUMBER) IS

BEGIN
    INSERT INTO bonificacao VALUES (CODIGO, VALOR);
    DBMS_OUTPUT.PUT_LINE('Bonificação de coódigo ' || CODIGO || 'e valor' || VALOR || ' CADASTRADA COM SUCESSO!');
END;

-- Cadastrar comprador   ok
CREATE OR REPLACE TYPE myarray IS VARRAY(10) OF VARCHAR2(15);

CREATE OR REPLACE PROCEDURE CADASTRAR_COMPRADOR (CPF VARCHAR2, NOME VARCHAR2, SOCIAL_INSTA VARCHAR2, SOCIAL_FACE VARCHAR2, CONTATO myarray) IS

BEGIN
    INSERT INTO comprador values (CPF, NOME, SOCIAL_INSTA, SOCIAL_FACE);
    FOR I IN 1 ..  contato.COUNT LOOP
        INSERT INTO contato (CPF, CONTATO(I));
    END
    DBMS_OUTPUT.PUT_LINE('COMPRADOR CADASTRADO COM SUCESSO');
END

-- Cadastrar Hotel  OK
CREATE OR REPLACE PROCEDURE CADASTRAR_HOTEL (ID_HOTEL VARCHAR2, ID_DESTINO VARCHAR2, VALOR NUMBER) IS 
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT FROM destino WHERE ID = ID_DESTINO;
    IF CNT > 0 THEN
        INSERT INTO hotel VALUES(ID_HOTEL, ID_DESTINP, VALOR);
        DBMS_OUTPUT.PUT_LINE('HOTEL CADASTRADO COM SUCESSO BEBE S2');
    ELSE
        DBMS_OUTPUT.PUT_LINE('DESTINO NÃO LOCALIZADO');
    END IF;
END;

-- CADASTRAR SEGURO   OK

CREATE OR REPLACE PROCEDURE CADASTRAR_SEGURO (ID VARCHAR2, VALOR NUMBER) IS

BEGIN
    INSERT INTO SEGURO VALUES (ID, VALOR);
    DBMS_OUTPUT.PUT_LINE('SEGURO ' || ID || ' CADASTRADO COM SUCESSO!');
END


-- Quantidade de viagens feitas por um cliente
CREATE OR REPLACE FUNCTION NUM_VIAGENS (CPF2 VARCHAR2) RETURN NUMBER IS
NUM NUMBER := 0;

CURSOR CUR IS (SELECT codPacote FROM compra WHERE CPF_comprador = CPF2);
BEGIN
    OPEN CUR;
    FETCH CUR INTO codPacote
    WHILE CUR%FOUND LOOP
        NUM := NUM + 1;
        FETCH CUR INTO codPacote
    END LOOP
    RETURN NUM:
END;

-- Quantidade de Hoteis por destino
CREATE OR REPLACE FUNCTION NUM_HOTEL (ID_DESTINO VARCHAR2) RETURN NUMBER IS
NUM NUMBER := 0;

CURSOR CUR IS (SELECT ID FROM hotel WHERE IDdestino = ID_DESTINO);
BEGIN
    OPEN CUR;
    FETCH CUR INTO ID
    WHILE CUR%FOUND LOOP
        NUM := NUM + 1;
        FETCH CUR INTO ID
    END LOOP
    RETURN NUM:
END;
